### ISSUE TITLE
ButtonBoot turns off DS

### ISSUE THREAD

**Issue by FlameKat53** [FlameKat53/ButtonBoot#2]
I have made this issue so i may remember to fix this in the future

**Comment by FlameAlt53** [comment]
At 3:50PM PST i can test the latest commit, hopefully it works, (it now actually inits Fat :P)

**Comment by FlameAlt53** [comment]
okay, Epicpkmn11 tested this for me and it didnt turn off the console, it just said `fatInitDefault Failed!`

**Comment by FlameAlt53** [comment]
(this was because the fat system wasn't included)
